- name: update docker daemon config
  lineinfile:
    dest: /etc/default/docker
    create: yes 
    line: 'DOCKER_OPTS="-s {{docker_backend_driver}}"'
  register: docker_daemon_config

- name: restart docker
  service: name=docker state=restarted
  when: docker_daemon_config.changed
