- name: install docker using docker shell script
  shell: curl -sSL https://get.docker.com/ | sh
  args:
    creates: /usr/bin/docker
  register: docker_installed

- name: Update facts
  setup: ''
  when: docker_installed.changed or ansible_docker0 is not defined
