- include_vars: btrfs.yml
  when: docker_use_btrfs_partition
- include_vars: devicemapper.yml
  when: not docker_use_btrfs_partition

- include: install.yml

- include: daemon_config.yml

- include: mount_partition.yml
  when: docker_use_btrfs_partition

- include: cleanup.yml
